title: Muskaan Sharma
logo: /assets/img/Picture.jpg
description:
  <p align="center">
  <a href="/assets/img/Muskaan_Sharma_Resume_updated(1)(1).pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/muskaan-sharma1999/">LinkedIn</a> |
  <a href="https://github.com/MuskaanSharma1308">GitHub</a>
  
  <br>   
 Worked as Solution Consultant at Lyra Infosystems.
 Currently I'm doing AI and ML course from IIIT Bangalore
 Also I have done Post Graduate Diploma In Data Science from Manipal University
 Skills: Python ,SQL ,Machine learning, Tableau ,NLP
 
 
  <br>
  </p>


theme: jekyll-theme-minimal
