title: Muskaan Sharma
logo: /assets/img/Picture.jpg
description:
  <p align="center">
  <a href="/assets/img/Muskaan_Sharma_Resume_updated(1)(1).pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/muskaan-sharma1999/">LinkedIn</a> |
  <a href="https://github.com/MuskaanSharma1308">GitHub</a>
  
 <br>   
  
   Skills: Python,SQL , Java , Machine Learning,NLP,AI,Machine Learning, Big Data , Tableau
  Worked as Open Source Auditor Pursuing AI and ML Course from IIIT Bangalore . POST Graduate Diploma in Data Science from Manipal University. Always open to learn new technology
 


 
 
  </br>
  
  
  
  </p>


theme: jekyll-theme-minimal
