title: Muskaan Sharma
logo: /assets/img/passportSizePhotoNew.jpg
description:
  <p align="center">
  <a href="pdf/resume.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/v-s-s-anirudh-sharma-ab405617b/">LinkedIn</a> |
  <a href="https://github.com/MuskaanSharma1308">GitHub</a>
  
  <br>   
 Worked as Solution Consultant at Lyra Infosystems
 
  <br>
  </p>


theme: jekyll-theme-minimal
